export * from "./Assignment.interface";
export * from "./Course.interface";
export * from "./Criteria.interface";
export * from "./Rubric.interface";
export * from "./Submission.interface";
export * from "./Teacher.interface";
export * from "./User.interface";
export * from "./Activity.interface";
export * from "./Evaluation.interface";
